"""
KisaanDrishti AI AWS Bedrock Explanation Service
======================================
Uses AWS Bedrock Converse API to convert structured
prescription results and weather into plain-language farmer explanations.
"""

import boto3
import asyncio
from botocore.exceptions import ClientError
from app.core.config import get_settings
from app.services.stcr_engine import PrescriptionResult, SoilInput
from typing import Dict, Optional
import logging

logger = logging.getLogger(__name__)
settings = get_settings()

bedrock_client = None
if settings.AWS_ACCESS_KEY_ID:
    try:
        bedrock_client = boto3.client(
            service_name="bedrock-runtime",
            region_name=settings.AWS_REGION,
            aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
            aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
        )
    except Exception as e:
        logger.error(f"Failed to initialize Boto3 client: {e}")

SYSTEM_PROMPT_EN = """You are KisaanDrishti AI, an expert agronomist assistant for farmers in India.

Your job is to EXPLAIN a fertilizer prescription generated by a scientific STCR engine.
STRICT RULES:
1. You MUST NOT invent any numeric doses. Use ONLY the given numbers.
2. Use RICH MARKDOWN formatting (bold text, lists, headers) to make the text highly readable and well-structured.
3. Be comprehensive and detailed. Explain WHY each fertilizer is needed and the scientific benefit.
4. I will provide you with TODAY'S fully detailed hourly weather data. Analyze it deeply and provide an EXACT recommended time window *today* to go out and apply the fertilizer (look for periods < 35°C, no rain). If today is completely unsafe, state exactly why based on the hourly data.
"""

SYSTEM_PROMPT_HI = """आप KisaanDrishti AI हैं, भारत के किसानों के लिए एक कृषि विशेषज्ञ।

आपका काम है वैज्ञानिक STCR इंजन द्वारा उत्पन्न उर्वरक prescription को समझाना।
सख्त नियम:
1. आप कोई भी संख्या (मात्रा) स्वयं नहीं बनाएंगे।
2. पाठ को अत्यधिक पठनीय और अच्छी तरह से संरचित बनाने के लिए समृद्ध मार्कडाउन (MARKDOWN) स्वरूपण (बोल्ड टेक्स्ट, सूचियां, हेडर) का उपयोग करें।
3. व्यापक और विस्तृत रहें। समझाएं कि प्रत्येक उर्वरक क्यों आवश्यक है और विज्ञान क्या है।
4. मैं आपको आज के मौसम का घंटे-दर-घंटे डेटा प्रदान करूंगा। इसका विश्लेषण करें और आज छिड़काव के लिए सबसे अच्छा समय सुझाएं (जब तापमान 35°C से कम हो और बारिश न हो)।
"""

def _build_prescription_summary(soil: SoilInput, result: PrescriptionResult, weather: Optional[Dict], farm_size: float = 1.0, farm_unit: str = "Hectare") -> str:
    lines = [
        f"Crop: {soil.crop_name} | Target Yield: {soil.target_yield_q_ha} q/ha",
        f"Farm Size: {farm_size} {farm_unit}",
        f"Soil: N={soil.n_kg_ha}, P={soil.p_kg_ha}, K={soil.k_kg_ha}",
        "PRESCRIPTION (Rates scaled to Farm Size):",
    ]
    
    # Calculate scale factor
    scale = 1.0
    if farm_unit.lower() == "acre":
        scale = farm_size * 0.404686
    elif farm_unit.lower() == "bigha":
        scale = farm_size * 0.25
    else:
        scale = farm_size

    for p in result.products_chemical:
        total_kg = p.kg_per_ha * scale
        lines.append(f"  - {p.product_name}: {p.kg_per_ha} kg/ha (TOTAL REQUIRED: {total_kg:.1f} kg) [{p.application_timing}]")
    
    if result.warnings:
        lines.append("\nWARNINGS:")
        for w in result.warnings:
            lines.append(f"  - {w}")
            
    if weather and "today_hourly" in weather:
        lines.append("\n--- TODAY'S HOURLY WEATHER DATA ---")
        for hr in weather["today_hourly"]:
            lines.append(f"Time: {hr['time']} | Temp: {hr['temp']}C | Precip: {hr['precip_mm']}mm")
        lines.append("----------------------------------\n")
            
    return "\n".join(lines)


def _invoke_bedrock_converse(system_prompt: str, user_message: str) -> str:
    if not bedrock_client:
        raise ValueError("Bedrock client not initialized")
    try:
        response = bedrock_client.converse(
            modelId=settings.BEDROCK_NOVA_PRO_ID,
            messages=[{"role": "user", "content": [{"text": user_message}]}],
            system=[{"text": system_prompt}],
            inferenceConfig={"temperature": 0.3, "maxTokens": 500}
        )
        return response["output"]["message"]["content"][0]["text"]
    except ClientError as e:
        logger.error(f"Bedrock API error: {e}")
        raise e

async def generate_explanation(soil: SoilInput, result: PrescriptionResult, language: str = "en", weather: Optional[Dict] = None, farm_size: float = 1.0, farm_unit: str = "Hectare") -> str:
    if not bedrock_client:
        return _fallback_explanation(soil, result, language)

    summary = _build_prescription_summary(soil, result, weather, farm_size, farm_unit)
    system_prompt = SYSTEM_PROMPT_HI if language == "hi" else SYSTEM_PROMPT_EN
    user_message = f"Please explain this prescription to the farmer. IMPORTANT: You must explicitly mention the total kilograms required for their specific {farm_size} {farm_unit} farm size as calculated in the payload below.\n\n{summary}"

    try:
        # Run synchronous boto3 call in thread pool to not block asyncio event loop
        explanation = await asyncio.to_thread(_invoke_bedrock_converse, system_prompt, user_message)
        return explanation
    except Exception as e:
        logger.error(f"LLM Generation failed: {e}")
        return _fallback_explanation(soil, result, language)


CHAT_SYSTEM_PROMPT = """You are KisaanDrishti AI, a helpful and expert agriculture assistant for Indian farmers.
Answer questions about crops, soil, pests, weather, and general farming practices.
Be polite, professional, and explain concepts simply.
Use MARKDOWN for clear formatting.
If asked about specific fertilizer doses, mention that they should use the 'Fertilizer Advisor' tool for a scientific calculation based on their soil test.
"""

async def get_chat_response(message: str, language: str = "en") -> str:
    if not bedrock_client:
        return "I'm sorry, my AI processing engine is currently offline. Please try again later."
    
    system_prompt = CHAT_SYSTEM_PROMPT
    if language == "hi":
        system_prompt += "\nकृपया हिंदी में उत्तर दें।"

    try:
        response = await asyncio.to_thread(_invoke_bedrock_converse, system_prompt, message)
        return response
    except Exception as e:
        logger.error(f"Chat generation failed: {e}")
        return "I encountered an error while processing your request. Please try again."

async def generate_weather_report(weather: Dict, language: str = "en") -> str:
    """Generate a comprehensive weather report/advisory for a farmer."""
    if not bedrock_client:
        return "Weather analysis is currently offline. Please check the raw data below."

    system_prompt = """You are KisaanDrishti AI Weather Expert. 
Your task is to analyze weather data and provide a detailed SITUATIONAL REPORT for a farmer.
Explain what the weather means for:
1. Irrigation (Should they water or will rain be enough?)
2. Fertilizer application (Is it safe to apply or will it wash away?)
3. Pest risk (Does high humidity or heat suggest pest outbreaks?)
4. Harvesting (Is the weather clear enough for drying crops?)
Use RICH MARKDOWN with headers, bold text, and bullet points. Be professional and encouraging.
"""
    if language == "hi":
        system_prompt += "\nकृपया हिंदी में विस्तार से उत्तर दें।"

    # Build a concise summary for the LLM
    daily = weather.get("daily", [])
    today_h = weather.get("today_hourly", [])
    
    summary_lines = ["WEATHER DATA OVERVIEW:"]
    for d in daily[:3]: # Next 3 days
        summary_lines.append(f"- Date: {d['date']} | Max: {d['temp_max']}C | Min: {d['temp_min']}C | Rain: {d['precipitation_mm']}mm | Prob: {d['precip_prob_pct']}%")
    
    if today_h:
        summary_lines.append("\nTODAY'S HOURLY PEAKS (Humidity & Wind):")
        # Extract max wind and avg humidity for brevity
        humidities = [h['humidity'] for h in today_h if 'humidity' in h]
        winds = [h['wind_speed'] for h in today_h if 'wind_speed' in h]
        avg_h = sum(humidities)/len(humidities) if humidities else 0
        max_w = max(winds) if winds else 0
        summary_lines.append(f"- Avg Humidity: {avg_h:.1f}% | Max Wind: {max_w:.1f} km/h")

    user_message = "\n".join(summary_lines)

    try:
        explanation = await asyncio.to_thread(_invoke_bedrock_converse, system_prompt, user_message)
        return explanation
    except Exception as e:
        logger.error(f"Weather report generation failed: {e}")
        return "Failed to generate AI weather report. Please check raw forecast charts."


def _fallback_explanation(soil: SoilInput, result: PrescriptionResult, language: str) -> str:
    lines = [f"Analysis for {soil.crop_name}:"]
    for p in result.products_chemical:
        lines.append(f"- {p.product_name}: {p.kg_per_ha} kg/ha ({p.application_timing})")
    return "\n".join(lines)
